FROM amazoncorretto:21

WORKDIR /app

COPY target/photoarchival-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 5000

ENV MONGODB_PORT=${MONGODB_PORT}
ENV MONGODB_HOST=${MONGODB_HOST}
ENV MONGODB_DATABASE=${MONGODB_DATABASE}
ENV MONGODB_USERNAME=${MONGODB_USERNAME}
ENV MONGODB_PASSWORD=${MONGODB_PASSWORD}
ENV MONGODB_AUTHENTICATION_DATABASE=${MONGODB_AUTHENTICATION_DATABASE}
ENV AWS_REGION=${AWS_REGION}
ENV AWS_BUCKET_NAME=${AWS_BUCKET_NAME}

CMD ["java", "-jar", "app.jar"]