spring:
  application:
    name: photoarchival
  cloud:
    aws:
      credentials:
        access-key: ANUJDEKAVADIYAEXAMPLE   # localstack credentials
        secret-key: 2QvM4/Tdmf38SkcD/qalvXO4EXAMPLEKEY # localstack credentials
      endpoint:
        uri: http://localhost:4566

  data:
    mongodb:
      database: photoarchival
      host: localhost
      port: 27017
      username: root
      password: example
      authentication-database: admin

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server.port: 8080

aws:
  bucket:
    name: bucket
